<a href="https://colab.research.google.com/github/h1mmeister/Machine_Learning/blob/main/00_tensorflow_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Introductions to Tensors

In [1]:
# Import Tensorflow
import tensorflow as tf
print(tf.__version__)

2.4.1


In [2]:
# Create tensors from tf.constant()
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [3]:
# Check the number iof dimensions of a tensor (ndim stands for number of dimensions)
scalar.ndim

0

In [4]:
# Create a vector
vector = tf.constant([10, 10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [5]:
# Check the dimensions of the vector
vector.ndim

1

In [6]:
# Create a matrix
matrix = tf.constant([[10, 7], [7, 10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [7]:
# Check the dimensions of the matrix
matrix.ndim

2

In [8]:
# Create another matrix and sepecify the dtype
another_matrix = tf.constant([[10., 7.], [1., 2.,], [9., 5.]], dtype = tf.float16)
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 1.,  2.],
       [ 9.,  5.]], dtype=float16)>

In [9]:
# Dimension of another matrix
another_matrix.ndim

2

In [10]:
# Create a tensor
tensor = tf.constant([[[1,2,3],[4,5,6]], [[1,3,5],[2,4,6]], [[1,5,9],[3,5,8]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 3, 5],
        [2, 4, 6]],

       [[1, 5, 9],
        [3, 5, 8]]], dtype=int32)>

In [11]:
# Check the dimensions of tensor
tensor.ndim

3

### Creating tensors with `tf.Variable`

In [12]:
tf.Variable

tensorflow.python.ops.variables.Variable

In [13]:
# Create the same tensor with tf.Variable
change_tensor = tf.Variable([10,7])
unchange_tensor = tf.constant([10, 7])
change_tensor, unchange_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [14]:
# Let's change one of the elements in the change_tensor
change_tensor[0] = 7

TypeError: ignored

In [16]:
# We can use the .assign function
change_tensor[0].assign(7)
change_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

In [17]:
# Let's try to change the unchange tensor
unchange_tensor[0] = 7

TypeError: ignored

In [18]:
unchange_tensor[0].assign(7)

AttributeError: ignored

### Creating random tensors


Random tensors are tensors of some arbitary size which contains random numbers.

In [22]:
# Create two random tensors
random_one = tf.random.Generator.from_seed(42) # set seed for reproducibility
random_one = random_one.normal(shape = (3, 2))

random_two = tf.random.Generator.from_seed(42)
random_two = random_two.normal(shape = (3, 2))

random_one, random_two, random_one == random_two

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)